### ISSUE TITLE
Handle all server event types

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#256]
- [x] message
- [x] update_message
- [x] subscription
- [x] heartbeat
- [x] presence
- [x] update_message_flags

Highly useful:
- [ ] stream (Useful for keeping up-to-date which streams exist or the user is subscribed to for purposes of autocomplete, managing streams drawer, etc.).
 **TODO: Handle EVENT_STREAM_ADD, EVENT_STREAM_REMOVE, EVENT_STREAM_UPDATE**
- [ ] realm_user (Useful for keeping up-to-date the membership of the realm for purposes of autocomplete etc.)
**TODO: Handle EVENT_USER_REMOVE, EVENT_USER_UPDATE**

Useful:
- [x] update_message_flags (Used for tracking which messages are read/unread, starred, mention the user, etc.).  Listed above, though?
- [ ] muted_topics (Controls whether messages to a given stream/topic pair should be hidden.  It's managed entirely by frontend, so needs to be implemented in the app)

Marginally useful:
- [ ] update_display_settings (Includes changes for whether time format should be 24-hour or AM/PM).
- [ ] realm_emoji (Could update the local client's list of realm-specific emoji which in theory should eventually be added to the emoji picker)
- [ ] update_global_notifications (Used only for notification settings; one might want to manage the "send offline/online mobile push notifications" setting from the app eventually, but not a priority)
- [ ] realm (Contains updates to realm-level settings; most of these aren't super relevant).  zerver/views/update_realm is a good reference for what these are; I think the first one we'll want is `realm.allow_message_editing` when we add message editing as a feature.

Useful only for local echo/markdown preview of messages:
- [ ] alert_words (an input to local echo)
- [ ] realm_filters (an input to local echo)

Not needed:
- [x] default_streams (not needed; just used for admin settings)
- [x] restart (not needed; used to tell browsers to reload for new JS)
- [x] referral (basically useless)
- [x] realm_domains (used only for administrator settings)
- [x] realm_bot (used only for bot administration which should probably stay web-only)

**Comment by borisyankov** [comment]
@timabbott I found that the `server_events.js` file useful. Is there documentation on what event does what somewhere?

**Comment by borisyankov** [comment]
Also, see the unchecked events that we do not handle yet. Is there something that is high priority?

**Comment by timabbott** [comment]
zerver/lib/actions.py has the code paths that send all of these; look for calls to `send_event`.  I'm updating the above with the stories for each.

**Comment by zulipbot** [comment]
Hello @borisyankov, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for 7 days. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by kunall17** [comment]
Its done, can be closed now!
