### ISSUE TITLE
Target Android SDK version 26

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#3075]
Beginning on 2018-11-01 -- that's next week -- any new release we upload to the Play Store must have `targetSdkVersion` set to 26 or higher.

This is a major change. It causes all systems running newer versions of Android than our previous target (22) to treat our app with a number of behavior changes introduced by the versions since then, up to the new target -- which means 6.0, 7.0, 7.1, and 8.0, aka Marshmallow, Nougat, and Oreo.  That's years of changes, with known and, surely, unknown changes that affect us. Here's a concise list of just the most important changes:
https://developer.android.com/distribute/best-practices/develop/target-sdk

I committed this change to master in 53970d46d, and released 19.0.100 to the alpha channel (on Android) with that change. That will help us find issues empirically. Now we need to find and fix them. :stuck_out_tongue: 

**UPDATE**: I've released 19.1.101 to Android alpha. It fixes the critical known issue that notifications completely didn't work (#3076). More testing needed for all the "known unknown" potential issues below, as well as to spot any others!

Here's a list, which I'll keep updated, of the things we need to do:
- [x] (@gnprice) Read through the [list of high-risk changes](https://developer.android.com/distribute/best-practices/develop/target-sdk) to find likely issues.
- [x] (@gnprice) Read through the more detailed "behavior changes" docs ([this one](https://developer.android.com/about/versions/marshmallow/android-6.0-changes) and later) for each release to find likely issues.
- [x] (everyone!) Play around with the ~19.0.100~ 19.1.101 alpha and look for issues.
- [x] (@gnprice, #3076) [Set channels on our notifications](https://developer.android.com/guide/topics/ui/notifiers/notifications#ManageChannels). In 19.0.100, notifications ~don't~ didn't work at all.
- [x] (filed as #3576) Test permissions behavior.
  - [x] (@gnprice) Read through the permissions in our output manifest, and compare to docs to find "dangerous" permissions and other potential pitfalls.
  - [x] (-> #3576) Test our use of the camera; test scenarios where the user first installs the app, we request permission, where the user then revokes permission, etc. See discussion of [dangerous permissions](https://developer.android.com/distribute/best-practices/develop/target-sdk#premarshmallow); and more detail [here](https://developer.android.com/guide/topics/permissions/overview#dangerous-permission-prompt) and usage notes [here](https://developer.android.com/training/permissions/usage-notes).
  - [x] (-> #3576) Test our use of the `WRITE_EXTERNAL_STORAGE` permission, similar to the camera; same docs apply. (For downloading files from the lightbox? Not 100% sure all the places this is used.)
  - [x] (-> #3576) Test our use of the `READ_EXTERNAL_STORAGE` permission, similar to the camera; same docs apply. (I think this applies when uploading an existing image. Not 100% sure if there are any other places.)
  - [x] (-> #3576) Test an install flow for any scary mentions of permissions. E.g., our manifest says we use [the `SYSTEM_ALERT_WINDOW` permission](https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW).
  - [x] (@gnprice) Understand our use (if any?) of `SYSTEM_ALERT_WINDOW`. Can we just remove it?
    - Answer: it's used by RN in debug builds, for displaying the debug menu. -> #3574 
- [x] (-> #3577) Test downloading files, and sharing images (i.e. our `shareImage`.) There's [a note about `file://` URLs](https://developer.android.com/about/versions/nougat/android-7.0-changes#permfilesys) which I *think* isn't an issue for downloading, but may be for our sharing; and I don't 100% understand what it's saying anyway. Some grepping finds `file://` URLs are used in several ways in `rn-fetch-blob`, which in turn we use in `downloadFile`, which is used in those two places.
- [x] (filed results as #3575) Test we behave properly when the user changes their system "Display size" and/or "Font size" settings while the app is already open. [See docs](https://developer.android.com/about/versions/nougat/android-7.0-changes#screen-zoom) of a change in how the system handles this.
- [x] (filed as #3571) ~~(low-priority) Update to [use `android:roundIcon`](https://developer.android.com/about/versions/nougat/android-7.1#circular-icons). #2993 is related. Empirically, on my device on stock Android 9, our icon with 19.0.100 shows up perfectly fine in the launcher the same as it always has, but maybe some launchers that prefer square icons will behave less well? Also the debug icon gets adjusted and looks less good, but that's a very low priority.~~

For later mop-up:
- [x] (filed as #3574) ~~Remove the `SYSTEM_ALERT_WINDOW` permission from the output manifest in release builds; it's only needed in debug builds, for displaying the RN debug menu.~~

**Comment by gnprice** [comment]
Fixed #3076 ! That was the one really critical known issue.

Earlier, I spent most of today reading through the docs, which is how I produced the bulk of the tasks in the description above.

Still lots of testing to be done! Details in the description.

**Comment by jackrzhang** [comment]
I've tested the most common installation scenario on my Android Virtual Device, which is preinstalled with the Play Store via a "Nexus 5 API 28" hardware profile and a corresponding 64-bit, API 28 system image.

Here's the Zulip application in the Play Store:

<img src="https://user-images.githubusercontent.com/12771126/47610964-44500d00-da17-11e8-9194-3a1744e2c8b9.png" width="300" />

Once I press "Install", a permissions modal appears.

<img src="https://user-images.githubusercontent.com/12771126/47610971-79f4f600-da17-11e8-98ee-32947a0736bd.png" width="300" />

If I press "Accept", the application installs, and uploading images both from the Camera and from Photos work as expected. The image below that was uploaded from the Camera also saved to Photos, as expected.

<img src="https://user-images.githubusercontent.com/12771126/47611015-f2a88200-da18-11e8-8024-fac273c13a2f.png" width="300" />

I'll continue to post test results on this thread!

**Comment by jackrzhang** [comment]
> Test we behave properly when the user changes their system "Display size" and/or "Font size" settings while the app is already open. See docs of a change in how the system handles this.

I've tested this on my emulator, running a Nexus 4 API 28 hardware profile, per the instructions from the [documentation](https://developer.android.com/about/versions/nougat/android-7.0-changes#screen-zoom):
> Users cannot zoom the screen past a minimum screen width of `sw320dp`, which is the width of a Nexus 4, a common medium-sized phone
> ...
> Test your app on a device with screen width `sw320dp` and be sure it performs adequately.

The application seemed to respond as expected - I changed either "Display size" or "Font size" in the settings, and the application UI updated automatically and accordingly across the entire interface.

As an observation, "Display size" on Android seems to correspond to the concept of "Display Zoom" on iOS, where a "Zoomed" view shows larger controls, and a "Standard" view shows more content.

One hitch I noticed was that the button currently labeled "Create group" ran out of space for the text when "Display size" was set to "Larger" (the largest option) and "Font size" was set to "Large" or "Largest":
<p align="center">
<img src="https://user-images.githubusercontent.com/12771126/48037884-1c515f80-e123-11e8-9a7f-7249d5b07c8e.png" width="320">
</p>

**Comment by borisyankov** [comment]
@gnprice That should be closed now?

**Comment by gnprice** [comment]
There are a lot of pieces in this issue, and many of them we have not done. That's why this issue is still open.

I think these would be best tracked as separate issues, so I'm splitting them out that way now. Then I'll close this issue, because the headline task is done (we did indeed set `targetSdkVersion` to 26, and resolved the one blocker-level followup which was #3076 .)

I've already filed #3574 and #3575 ; there are a couple more to come.

**Comment by gnprice** [comment]
@jackrzhang Thanks for your study of this back in October!

> I've tested the most common installation scenario

You don't mention in this test what version you were looking at. I think you may have been looking at a version that didn't yet target API 26:
* I'm not sure of the exact release history of versions that did, but my comment of 2018-10-25 marked the earliest that we had such a version that could have been sent to beta or prod. Your report is two days after that, consistent with either an old or a new version being out.
* The flow pictured is one that should only have happened with the old, low `targetSdkVersion`. From [this doc](https://developer.android.com/guide/topics/permissions/overview#dangerous-permission-prompt) linked above:
  > If the device is running Android 6.0 (API level 23) or higher, *and* the app's `targetSdkVersion` is 23 or higher, the user isn't notified of any app permissions at install time. Your app must ask the user to grant the dangerous permissions at runtime.

I've just filed #3576 for the task of testing permissions behavior and the install flow.

**Comment by gnprice** [comment]
And with #3577, the disaggregation is complete! Closing this.

See also #3563, which is the second annual round of the same thing. That one will hopefully be milder, though -- this one was four years' worth of platform changes all at once, and that meant we're more caught up so that this year's round will only be one year's worth of platform changes.
