### ISSUE TITLE
Tweak UI of mention-unsubscribed warning

### ISSUE THREAD

**Issue by gnprice** [zulip/zulip-mobile#4224]
This issue is to follow up on #4219 with some small UI improvements to the "$person will not be notified unless you subscribe them" warning which we added in #4101 (addressing #3373). Going through my comment at https://github.com/zulip/zulip-mobile/pull/4101#issuecomment-669764675 in order:
- [x] button shape/size in visual appearance -- done in #4219
- [ ] button touch target to 48px (extending beyond visual button) -- still TODO
- [x] no border -- done in #4219
- [ ] background color -- still TODO
- [x] text/background color contrast, for legibility -- done in #4101 before merge
- [x] cut animation -- done in #4219
- [ ] use a nice slide-in animation instead -- still TODO

See that comment for details on each of these. For the touch target, @chrisbobbe adds (at https://github.com/zulip/zulip-mobile/pull/4219#issuecomment-670784841 ) :
> For this, we'll likely want to use the [`hitSlop` prop](https://reactnative.dev/docs/view#hitslop) of the component that gets the `onPress` prop. We may have to adjust the dimensions of its parent, too:
> 
> > The touch area never extends past the parent view bounds and the Z-index of sibling views always takes precedence if a touch hits two overlapping views.

**Comment by Gautam-Arora24** [comment]
@gnprice I would love to work on this issue. I think there are small points left in this issue that will not take much time to complete. What's your take on this?

**Comment by chrisbobbe** [comment]
Sounds good! Thanks, @Gautam-Arora24.
