### ISSUE TITLE
Android Public Release

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#495]
- [ ] Everything for iOS #586
- [ ] Compose box correct sizing #457
- [ ] Performance issues, unknown cause #587
- [ ] Choppy Drawer animations. Will be fixed with #504
- [ ] Android 4.1-4.4 support #544

**Comment by vishwesh3** [comment]
Compose box correct sizing is fixed in https://github.com/zulip/zulip-mobile/pull/457

**Comment by divs4debu** [comment]
I have solved the 2 bugs that are marked should i send the pic ? @borisyankov

**Comment by divs4debu** [comment]
@borisyankov  have a look on this -
![satuts-bar](https://cloud.githubusercontent.com/assets/9443348/25306989/9462de86-27b6-11e7-83a9-4bc3cf6f2bdd.png)
![status-navigation](https://cloud.githubusercontent.com/assets/9443348/25306990/9463ceea-27b6-11e7-8e66-fefc3b48eef8.png)
Does they look fine?

**Comment by divs4debu** [comment]
@borisyankov  I have some updates Please review - 
![device-2017-04-23-101958](https://cloud.githubusercontent.com/assets/9443348/25310906/bf8124b2-280e-11e7-95f6-29e1acdd5be7.png)
![device-2017-04-23-102015](https://cloud.githubusercontent.com/assets/9443348/25310907/bf817fe8-280e-11e7-8bef-6c4c92c61d61.png)
![device-2017-04-23-102040](https://cloud.githubusercontent.com/assets/9443348/25310908/bf83a0b6-280e-11e7-9415-6a870d5c0275.png)
![device-2017-04-23-102056](https://cloud.githubusercontent.com/assets/9443348/25310909/bf8494bc-280e-11e7-9437-e4f92a1dcaa2.png)


The status bar color changes according to stream color and home has teal color . Is that good?

**Comment by borisyankov** [comment]
@divs4debu the issues that are checked are already resolved.

**Comment by divs4debu** [comment]
@borisyankov arent they merge yet ?

**Comment by borisyankov** [comment]
They are. The difference being that the statusbar for white header does not change color I think.

**Comment by divs4debu** [comment]
When i look around the code i noticed that in MainNavbar - 
`<StatusBar
          barStyle={textColor === 'white' ? 'light-content' : 'dark-content'}
        />`
now if text color isnt white it will switch to dark-content and background color is black by default and hence they are not visible. what we can do is 
`barStyle = "Default"`
link - [https://facebook.github.io/react-native/docs/statusbar.html](url) under "StatusBarStyle"
this would change according to platform default (i.e. light-content in android).  Moreover making a function that returns dark color of the stream and then set  -
`backgroundColor  = {dark(colorofstream)}`
this will make the status bar color dynamic.

**Comment by borisyankov** [comment]
Aaah, the StatusBar PR is not yet merged.

**Comment by zulipbot** [comment]
Hello @borisyankov, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for 7 days. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 3 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by vishwesh3** [comment]
#457,  #587, #504,  #544 got merged/closed/fixed. And Android release is public. We can close this too :)

**Comment by borisyankov** [comment]
:) Closing as done.
