### ISSUE TITLE
iOS Public Release

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#586]
- [ ] New messages arriving don't show in narrows #584 
- [ ] When keyboard pops up, anchor message list bottom #592
- [ ] Switching narrows should anchor message list to first unread message #583 
- [ ] Unread Messages flashes for a bit for self sent messages #588
- [x] Sometimes numbers in emoji reactions are not aligned correctly #589
- [x] Sometimes the emoji reactions don't work/do anything when clicked on. #590
- [x] App Store Requirements #591

**Comment by gnprice** [comment]
The linked issues are all closed, and the app has been out in public for some time. Closing; we have plenty of specific threads for specific issues in the iOS app.
