### ISSUE TITLE
Better Compose Box

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#595]
- [ ] Keyboard shown in compose box should push stream content up #180
- [x] Compose box should allow choosing of topic #163 
- [x] Smart placeholder for compose input #594
- [x] Auto complete suggestions are not being displayed outside the compose box for Android #579 
- [ ] Thumbs up button when no text in compose box #517 (to discuss)

**Comment by borisyankov** [comment]
Closing as mostly accomplished. Will track the list in other ways.
