### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by borisyankov** [zulip/zulip-mobile#604]
- [ ] Sometimes the emoji reactions don't work/do anything when clicked on. #590
- [ ] Sometimes numbers in emoji reactions are not aligned correctly #589
- [ ] Automatically replace common emoji shortcuts to actual emojis #516
- [ ] Show placeholder when custom emoji unavailable #186
- [ ] Support new server emojis #603
- [ ] Get custom emojis from realm #607

**Comment by vishwesh3** [comment]
Can be closed now
only #186 is remaining

**Comment by borisyankov** [comment]
Closing as complete.
